# Copyright 2022 the Gigamono authors. All rights reserved. GPL-3.0 License.

version: "3.9"
services:
  nats:
    restart: always
    container_name: nats
    image: nats:latest
    expose:
      - "4222"
    networks:
      - gigamono

  db:
    restart: always
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - gigamono

  engine_proxy:
    container_name: engine_proxy
    image: engine_proxy
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    build:
      context: ../../
      dockerfile: docker/engine_proxy/Dockerfile
    ports:
      - "5050"
    volumes:
      - type: bind
        source: ../../
        target: /mount
    depends_on:
      - nats
      - db
    networks:
      - gigamono

  engine_workspace:
    container_name: engine_workspace
    image: engine_workspace
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    build:
      context: ../../
      dockerfile: docker/engine_workspace/Dockerfile
    expose:
      - "5051"
    volumes:
      - type: bind
        source: ../../
        target: /mount
    depends_on:
      - nats
      - db
    networks:
      - gigamono

  engine_backend:
    container_name: engine_backend
    image: engine_backend
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    build:
      context: ../../
      dockerfile: docker/engine_backend/Dockerfile
    expose:
      - "5052"
    volumes:
      - type: bind
        source: ../../
        target: /mount
    depends_on:
      - nats
      - db
    networks:
      - gigamono

networks:
  gigamono:
    name: gigamono

volumes:
  db:
