version: "3.9"
services:
  nats:
    restart: always
    container_name: nats
    image: nats
    expose:
      - "4222"
    networks:
      - nats

  engine_proxy:
    container_name: engine_proxy
    image: gigamono/engine_proxy:latest
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    ports:
      - "5050:5050"
    volumes:
      - type: bind
        source: ../../
        target: /mount
    links:
      - nats
    networks:
      - nats

  engine_workspace:
    container_name: engine_workspace
    image: gigamono/engine_workspace:latest
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    expose:
      - "5051"
    volumes:
      - type: bind
        source: ../../
        target: /mount
    links:
      - nats
    networks:
      - nats

  engine_backend:
    container_name: engine_backend
    image: gigamono/engine_backend:latest
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    expose:
      - "5052"
    volumes:
      - type: bind
        source: ../../
        target: /mount
    links:
      - nats
    networks:
      - nats

networks:
  nats:
    name: nats
