# TODO(appcypher): Use volumes properly
version: "3.9"
services:
  nats:
    restart: always
    image: nats
    expose:
      - "4222"
    hostname: nats
    networks:
      - nats

  engine_proxy:
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    build:
      context: ../../
      dockerfile: docker/engine_proxy/Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - nats
    networks:
      - nats

  engine_workspace:
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    build:
      context: ../../
      dockerfile: docker/engine_workspace/Dockerfile
    expose:
      - "5051"
    depends_on:
      - nats
    networks:
      - nats

  engine_backend:
    environment:
      - GIGAMONO_CONFIG_PATH
      - RUST_LOG
    build:
      context: ../../
      dockerfile: docker/engine_backend/Dockerfile
    expose:
      - "5052"
    volumes:
      - ../../sample:/app/sample
    depends_on:
      - nats
    networks:
      - nats

networks:
  nats:
    name: nats
